/*
    Sakshee Phade, 43244, BE R 10
    PROBLEM STATEMENT : Write a program in C++ or java to implement SHA1 algorithm using libraries (API)  
*/

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.*;  

public class SHA1 {
	public static String encryptThisString(String input)
	{
		try {
			// getInstance() method is called with algorithm SHA-1
			MessageDigest md = MessageDigest.getInstance("SHA-1");
			// digest() method is called
			// to calculate message digest of the input string
			// returned as array of byte
			byte[] messageDigest = md.digest(input.getBytes());

			BigInteger no = new BigInteger(1, messageDigest); //convert byte array messageDigest into text
            
            System.out.print("\nBig " + no);
			// Convert message digest into hex value
			String hashtext = no.toString(16);

			// Add preceding 0s to make it 32 bit
			while (hashtext.length() < 32) {
				hashtext = "0" + hashtext;
			}

			// return the HashText
			return hashtext;
		}

		// For specifying wrong message digest algorithms
		catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		}
	}

	// Driver code
	public static void main(String args[]) throws
									NoSuchAlgorithmException
	{

		
        Scanner sc = new Scanner(System.in); //System.in is a standard input stream  
        
        System.out.print("\n============================================================\n");
        System.out.print("\nEnter a string: ");  
        String str= sc.nextLine();              //reads string  

        System.out.println("HashCode Generated by SHA-1 for: ");
		System.out.println("\n" + str + " : " + encryptThisString(str));

		String s2 = "Hello, World!";
		System.out.println("\n" + s2 + " : " + encryptThisString(s2));
        System.out.print("\n============================================================\n");

		sc.close();
	}
}

/*

OUTPUT :

E:\BE\CL7_ICS>java SHA1

============================================================

Enter a string: Sakshee Phade
HashCode Generated by SHA-1 for: 

Sakshee Phade : e03b327784b15f889bce3f877edc1356d5495831

Hello, World! : a0a9f2a6772942557ab5355d76af442f8f65e01

============================================================

E:\BE\CL7_ICS>

*/